"""empty message

Revision ID: 75ddba2fbe1f
Revises: e2ef7c893896
Create Date: 2026-02-25 11:46:10.550866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ddba2fbe1f'
down_revision: Union[str, Sequence[str], None] = 'e2ef7c893896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bonuses_employee_id_fkey'), 'bonuses', type_='foreignkey')
    op.create_foreign_key(None, 'bonuses', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('deductions_employee_id_fkey'), 'deductions', type_='foreignkey')
    op.create_foreign_key(None, 'deductions', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deductions', type_='foreignkey')
    op.create_foreign_key(op.f('deductions_employee_id_fkey'), 'deductions', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'bonuses', type_='foreignkey')
    op.create_foreign_key(op.f('bonuses_employee_id_fkey'), 'bonuses', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
