"""added journal_entry_id to VendorInvoice

Revision ID: e2ef7c893896
Revises: bb71924e49fc
Create Date: 2025-10-29 10:56:23.346040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ef7c893896'
down_revision: Union[str, Sequence[str], None] = 'bb71924e49fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_invoices', sa.Column('journal_entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendor_invoices', 'journal_entries', ['journal_entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_invoices', type_='foreignkey')
    op.drop_column('vendor_invoices', 'journal_entry_id')
    # ### end Alembic commands ###
